[package]
name = "ferrox-types"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
documentation.workspace = true
description = "Standardized domain primitives, type-safe PublicId identifiers, and Pagination models for Ferrox."
[dependencies]
serde.workspace = true
validator = { version = "0.18", features = ["derive"] }
ferrox-errors = { version = "0.1.0", path = "../ferrox-errors"  }
ts-rs.workspace = true
