[package]
name = "yalc-logger"
version.workspace = true
edition.workspace = true

[dependencies]
tracing.workspace = true
tracing-subscriber = { version = "0.3", features = ["env-filter", "json"] }
opentelemetry = { version = "0.21" }
opentelemetry_sdk = { version = "0.21", features = ["rt-tokio"] }
opentelemetry-otlp = { version = "0.14", features = ["tonic"] }
tracing-opentelemetry = "0.22"
sentry = { version = "0.34" }
sentry-tracing = { version = "0.34" }
yalc-errors = { path = "../yalc-errors" }
