[package]
name = "yalc-ag-grid-seaorm"
version.workspace = true
edition.workspace = true

[dependencies]
sea-orm = { workspace = true, features = ["sqlx-postgres", "runtime-tokio-rustls", "macros"] }
yalc-ag-grid-core = { path = "../yalc-ag-grid-core" }
yalc-errors = { path = "../../yalc-errors" }

[dev-dependencies]
serde_json = "1.0"
