[package]
name = "ferrox-database-seaorm"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
documentation.workspace = true
description = "Relational database repository implementation powered by SeaORM (PostgreSQL, MySQL, SQLite)."
[dependencies]
sea-orm = { workspace = true, features = ["sqlx-postgres", "runtime-tokio-rustls", "macros"] }
log = "0.4"
ferrox-database-core = { version = "0.1.0", path = "../ferrox-database-core"  }
ferrox-errors = { version = "0.1.0", path = "../../ferrox-errors"  }
