[workspace]
members = [
    "crates/ferrox-app",
    "crates/ferrox-errors",
    "crates/ferrox-logger",
    "crates/ferrox-crud-gen",
    "crates/ferrox-graphql",
    "crates/ferrox-events",
    "crates/ferrox-utils",
    "crates/ferrox-types",
    "crates/ferrox-security",
    "crates/ferrox-metrics",
    "crates/database/ferrox-database-core",
    "crates/database/ferrox-database-seaorm",
    "crates/database/ferrox-database-mongo",
    "crates/database/ferrox-database-redis",
    "crates/ferrox-datagrid",
    "crates/ferrox-validation",
    "crates/ferrox-saga",
    "crates/ferrox-search",
    "crates/ferrox-integrations",
    "crates/ferrox-interceptors",
    "crates/ferrox-schedule",
    "crates/ferrox-sse",
    "crates/ferrox-singleflight",
    "crates/ferrox-health",
    "crates/ferrox-tracing",
    "crates/ferrox-config",
    "crates/ferrox-i18n",
    "crates/ferrox-circuit-breaker",
    "crates/ferrox-migrations",
    "crates/ferrox-sync",
    "crates/ferrox-guards",
    "crates/ferrox-storage",
    "crates/ferrox-cqrs",
    "crates/ferrox-cli",
    "crates/integrations/ferrox-notifications-slack",
    "crates/integrations/ferrox-payments-stripe",
    "crates/integrations/ferrox-payments-google",
    "crates/integrations/ferrox-storage",
    "crates/integrations/ferrox-mailer",
    "crates/integrations/ferrox-feature-flags",
    "crates/integrations/ferrox-reports",
    "crates/integrations/ferrox-cloud-helpers",
    "crates/integrations/ferrox-webhooks",
    "crates/ferrox-jobs",
    "crates/ferrox-rate-limiter",
    "apps/ferrox-showcase"
]

[workspace.package]
version = "0.1.0"
edition = "2021"
authors = ["Antigravity"]

[workspace.dependencies]
axum = "0.7"
tokio = { version = "1", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
tracing = "0.1"
thiserror = "1.0"
anyhow = "1.0"
sea-orm = { version = "1.0" }
async-graphql = "7.0"
time = { version = "0.3", features = ["serde", "formatting", "macros"] }
ts-rs = "8.1"

[workspace.lints.clippy]
pedantic = "warn"
unwrap_used = "deny"
