[package]
name = "ferrox-validation"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
description = "Enterprise module ferrox-validation for Ferrox Framework."
[dependencies]
axum = { version = "0.7" }
serde = { version = "1.0", features = ["derive"] }
validator = { version = "0.16", features = ["derive"] }
ferrox-errors = { version = "0.1.0", path = "../ferrox-errors"  }
async-trait = "0.1"
