[package]
name = "ferrox-database-mongo"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
documentation.workspace = true
description = "Enterprise module ferrox-database-mongo for Ferrox Framework."
[dependencies]
mongodb = { workspace = true }
tokio = { workspace = true, features = ["full"] }
ferrox-database-core = { version = "0.1.0", path = "../ferrox-database-core"  }
ferrox-errors = { version = "0.1.0", path = "../../ferrox-errors"  }
