[package]
name = "ferrox-database-dynamo"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
documentation.workspace = true
description = "DynamoDB NoSQL repository connector for Ferrox ecosystem."

[dependencies]
ferrox-database-core = { version = "0.7.0", path = "../ferrox-database-core" }
ferrox-errors = { version = "0.7.0", path = "../../ferrox-errors" }
tokio = { workspace = true }
async-trait = { workspace = true }
log = "0.4"
# Mocking aws-sdk-dynamodb for boilerplate purposes
aws-sdk-dynamodb = "1.0"
serde_dynamo = { version = "4.2", features = ["aws-sdk-dynamodb+1"] }
serde = { workspace = true }
serde_json = { workspace = true }
