[package]
name = "ferrox-transports"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
documentation.workspace = true
description = "Enterprise module ferrox-transports for Ferrox Framework."
[features]
default = ["http", "grpc", "ftp"]
http = ["dep:axum", "dep:tokio"]
grpc = ["dep:tonic", "dep:prost", "dep:tokio"]
ftp = ["dep:suppaftp", "dep:tokio"]

[dependencies]
async-trait = "0.1"
ferrox-errors = { version = "0.1.0", path = "../ferrox-errors"  }
tower-http = { version = "0.5", features = ["cors"] }

# Optional Dependencies
axum = { version = "0.7", features = ["ws"], optional = true }
tokio = { version = "1.35", features = ["full"], optional = true }
tonic = { version = "0.10", optional = true }
prost = { version = "0.12", optional = true }
suppaftp = { version = "5.2", optional = true }
