[package]
name = "ferrox-metrics"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
documentation.workspace = true
description = "Enterprise module ferrox-metrics for Ferrox Framework."
[dependencies]
metrics = "0.22"
metrics-exporter-prometheus = "0.13"
tokio = { workspace = true, features = ["full"] }
ferrox-errors = { version = "0.1.0", path = "../ferrox-errors"  }
