[package]
name = "ferrox-security"
version.workspace = true
edition.workspace = true

[dependencies]
secrecy = "0.8"
argon2 = "0.5"
pasetors = "0.6"
rand_core = { version = "0.6", features = ["std"] }
serde = { workspace = true, features = ["derive"] }
serde_json = "1.0"
time = { workspace = true }
ferrox-errors = { path = "../ferrox-errors" }
axum = { version = "0.7" }
