[package]
name = "yalc-database-mongo"
version.workspace = true
edition.workspace = true

[dependencies]
mongodb = { version = "3.0", features = ["tokio-runtime"] }
tokio = { workspace = true, features = ["full"] }
yalc-database-core = { path = "../yalc-database-core" }
yalc-errors = { path = "../../yalc-errors" }
