[package]
name = "ferrox-cqrs"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
documentation.workspace = true
description = "Decoupled CommandBus and QueryBus dispatching architecture pattern for Ferrox."
[dependencies]
tokio = { version = "1", features = ["full"] }
async-trait = "0.1"
ferrox-errors = { version = "0.1.0", path = "../ferrox-errors"  }
tracing = "0.1"
