[package]
name = "ferrox-mailer"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
documentation.workspace = true
description = "Async email dispatcher client backed by Lettre (SMTP, AWS SES, SendGrid)."
[dependencies]
lettre = { version = "0.11", features = ["tokio1", "tokio1-native-tls", "builder"] }
ferrox-errors = { version = "0.1.0", path = "../../ferrox-errors"  }
