[package]
name = "ferrox-notifications-slack"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
documentation.workspace = true
description = "Slack incoming webhook alert dispatcher adapter for Ferrox."
[dependencies]
async-trait = "0.1"
ferrox-errors = { version = "0.1.0", path = "../../ferrox-errors"  }
ferrox-integrations = { version = "0.1.0", path = "../../ferrox-integrations"  }

# In a real app we'd use reqwest to call Slack Webhooks
# reqwest = { version = "0.11", features = ["json"] }
