[package]
name = "ferrox-storage"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
description = "Enterprise module ferrox-storage for Ferrox Framework."
[dependencies]
aws-config = "1.1"
aws-sdk-s3 = "1.21"
tokio = { workspace = true, features = ["full"] }
ferrox-errors = { version = "0.1.0", path = "../../ferrox-errors"  }
