[package]
name = "yalc-database-seaorm"
version.workspace = true
edition.workspace = true

[dependencies]
sea-orm = { workspace = true, features = ["sqlx-postgres", "runtime-tokio-rustls", "macros"] }
log = "0.4"
yalc-database-core = { path = "../yalc-database-core" }
yalc-errors = { path = "../../yalc-errors" }
