[package]
name = "ferrox-app"
version.workspace = true
edition.workspace = true

[dependencies]
axum = { workspace = true, features = ["tokio"] }
tokio = { workspace = true, features = ["full", "signal"] }
tower = "0.4"
tower-http = { version = "0.5", features = ["cors", "timeout", "catch-panic", "set-header"] }
ferrox-transports = { path = "../ferrox-transports" }
sentry-tower = { version = "0.34", features = ["http"] }
ferrox-errors = { path = "../ferrox-errors" }
