[package]
name = "ferrox-app"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
documentation.workspace = true
description = "Multi-transport application bootstrapper and graceful shutdown orchestrator for Axum & Tokio web applications."
[dependencies]
axum = { workspace = true, features = ["tokio"] }
tokio = { workspace = true, features = ["full", "signal"] }
tracing = "0.1"
tower = "0.4"
tower-http = { version = "0.5", features = ["cors", "timeout", "catch-panic", "set-header"] }
ferrox-transports = { version = "0.1.2", path = "../ferrox-transports"  }
sentry-tower = { version = "0.34", features = ["http"] }
ferrox-errors = { version = "0.1.1", path = "../ferrox-errors"  }
