[package]
name = "ferrox-saga"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
description = "Enterprise module ferrox-saga for Ferrox Framework."
[dependencies]
async-trait = "0.1"
ferrox-errors = { version = "0.1.0", path = "../ferrox-errors"  }
tracing = "0.1"

[dev-dependencies]
tokio = { version = "1.35", features = ["full"] }
