[package]
name = "yalc-datagrid"
version = "0.1.0"
edition = "2021"

[features]
default = ["seaorm", "aggrid", "mui", "tanstack"]
seaorm = ["dep:sea-orm"]
mongo = ["dep:mongodb", "dep:bson"]
aggrid = []
mui = []
tanstack = []

[dependencies]
yalc-errors = { path = "../yalc-errors" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

# Optional Translators
sea-orm = { workspace = true, optional = true }
mongodb = { workspace = true, optional = true }
bson = { workspace = true, optional = true }
