[package]
name = "ferrox-interceptors"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
documentation.workspace = true
description = "Request/response lifecycle interceptor pipeline and response caching middleware for Ferrox."
[dependencies]
async-trait = "0.1"
axum = "0.7"
tokio = { version = "1", features = ["full"] }
tracing = "0.1"
ferrox-database-redis = { version = "0.1.0", path = "../database/ferrox-database-redis"  }
ferrox-singleflight = { version = "0.1.0", path = "../ferrox-singleflight"  }
ferrox-security = { version = "0.1.0", path = "../ferrox-security"  }
secrecy = "0.8"
