[package]
name = "ferrox-integrations"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
description = "Enterprise module ferrox-integrations for Ferrox Framework."
[dependencies]
async-trait = "0.1"
ferrox-errors = { version = "0.1.0", path = "../ferrox-errors"  }
