[package]
name = "ferrox-rate-limiter"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
documentation.workspace = true
description = "Fixed window and token bucket rate limiters backed by Redis and memory."
[dependencies]
redis = { version = "0.25", features = ["tokio-comp"] }
tower = "0.4"
tokio = { workspace = true, features = ["full"] }
ferrox-errors = { version = "0.1.0", path = "../ferrox-errors"  }
