[package]
name = "yalc-app"
version.workspace = true
edition.workspace = true

[dependencies]
axum = { workspace = true, features = ["tokio"] }
tokio = { workspace = true, features = ["full", "signal"] }
tower = "0.4"
tower-http = { version = "0.5", features = ["cors", "timeout", "catch-panic", "set-header"] }
yalc-errors = { path = "../yalc-errors" }
