[package]
name = "yalc-notifications-slack"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = "0.1"
yalc-errors = { path = "../../yalc-errors" }
yalc-integrations = { path = "../../yalc-integrations" }

# In a real app we'd use reqwest to call Slack Webhooks
# reqwest = { version = "0.11", features = ["json"] }
